apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: DS_PROMETHEUS
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-datasource-config
              mountPath: /etc/grafana/provisioning/datasources/
      volumes:
        - name: grafana-datasource-config
          configMap:
            name: grafana-datasource-config
        
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: grafana